### ISSUE TITLE
enable frame plugin to request source data

### ISSUE THREAD

**Issue by dobbs** [dobbs/wiki-plugin-frame#10]
Proposed protocol sketched in http://trails.ward.asia.wiki.org/about-frame-lineup.html

Possible sink protocol for source data.
  
    SINK NEAREST region regionData
    SINK ALL region regionData

See http://trails.ward.asia.wiki.org/about-bikeshare-plugin.html

An html script would engage this with a request like this where source and method are optional if there is only one SINK markup.

    window.addEventListener("message", handler)
    let message = {
      action:"sendSourceData",
      source: "region",
      method: "regionData"
    }
    window.parent.postMessage(message, "*")

The Frame plugin will call the handler once for each request.

    function handler ({data}) {
      if (data.action == "sourceData") {
        window.removeEventListener("message", handler)
        {site, slug, item, responses} = data
        {north, south, east, west} = responses[0]
        ...
      }
    }

**Comment by WardCunningham** [comment]
My desire to read lineup "thing-source" from an html script has not waned even though my application of interest has shifted.

I am less interested in filtering map markers because I have discovered that the MAP plugin has no trouble displaying all of the markers I have. It was Journal bloat that was making my page slow.

I am now interested in replacing my /graphviz transporter with client-side rendering of Graph plugins using an html script in a Frame. The transporter uses this extra logic to gather graph-source to transport. [github](https://github.com/fedwiki/wiki-plugin-transport/blob/ac8aff34b2c157094204dfd193c9afd2dd2b9d41/client/transport.coffee#L13-L21)

![image](https://user-images.githubusercontent.com/12127/125387838-61f26b80-e353-11eb-845d-fdd9799d38ef.png)

I apply some additional heuristics to get pleasing composite diagrams which I am happy to port from ruby to javascript. We might eventually consider how to teach our own Graphviz plugin to do some of this but html scripting seems the better short-term goal. [github](https://github.com/WardCunningham/image-transporter/blob/2837af6c9b5fffa38f67ed00e805ca1baa14dd22/server.rb#L51-L83)

**Comment by dobbs** [comment]
versions 0.8.4 and 0.8.5 have implemented the `requestSourceData` action in postMessage handling.
https://github.com/dobbs/wiki-plugin-frame/blob/v0.8.7/client/frame.js#L258-L265
